angular.module("starter.controllers", [])
    .controller("LoginController", LoginController)
    .controller("ConfigController", ConfigController)
    .controller("TruckController", TruckController)
    .controller("TruckDetailController", TruckDetailController)
    .controller("JournalController", JournalController)
    .controller("JournalViewController", JournalViewController)
    .controller("MainController", MainController)